const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function countrySeeder() {
    const countries = [
        { code: "PYS-001", indicator: 93, name: "Afghanistan", description: "Pays d'Asie centrale, capitale Kaboul." },
        { code: "PYS-002", indicator: 27, name: "Afrique du Sud", description: "Pays d’Afrique australe, capitale Pretoria." },
        { code: "PYS-003", indicator: 355, name: "Albanie", description: "Pays d’Europe du Sud-Est, capitale Tirana." },
        { code: "PYS-004", indicator: 213, name: "Algérie", description: "Pays d’Afrique du Nord, capitale Alger." },
        { code: "PYS-005", indicator: 49, name: "Allemagne", description: "Pays d’Europe centrale, capitale Berlin." },
        { code: "PYS-006", indicator: 376, name: "Andorre", description: "Petit pays des Pyrénées, capitale Andorre-la-Vieille." },
        { code: "PYS-007", indicator: 244, name: "Angola", description: "Pays d’Afrique australe, capitale Luanda." },
        { code: "PYS-008", indicator: 1, name: "Antigua-et-Barbuda", description: "État insulaire des Caraïbes, capitale Saint John's." },
        { code: "PYS-009", indicator: 966, name: "Arabie Saoudite", description: "Pays du Moyen-Orient, capitale Riyad." },
        { code: "PYS-010", indicator: 54, name: "Argentine", description: "Pays d’Amérique du Sud, capitale Buenos Aires." },
        { code: "PYS-011", indicator: 374, name: "Arménie", description: "Pays du Caucase, capitale Erevan." },
        { code: "PYS-012", indicator: 61, name: "Australie", description: "Pays-continent d’Océanie, capitale Canberra." },
        { code: "PYS-013", indicator: 43, name: "Autriche", description: "Pays d’Europe centrale, capitale Vienne." },
        { code: "PYS-014", indicator: 994, name: "Azerbaïdjan", description: "Pays du Caucase, capitale Bakou." },
        { code: "PYS-015", indicator: 1, name: "Bahamas", description: "Archipel des Caraïbes, capitale Nassau." },
        { code: "PYS-016", indicator: 973, name: "Bahreïn", description: "État insulaire du Golfe persique, capitale Manama." },
        { code: "PYS-017", indicator: 880, name: "Bangladesh", description: "Pays d’Asie du Sud, capitale Dacca." },
        { code: "PYS-018", indicator: 1, name: "Barbade", description: "Île des Caraïbes, capitale Bridgetown." },
        { code: "PYS-019", indicator: 32, name: "Belgique", description: "Pays d’Europe de l’Ouest, capitale Bruxelles." },
        { code: "PYS-020", indicator: 501, name: "Belize", description: "Pays d’Amérique centrale, capitale Belmopan." },
        { code: "PYS-021", indicator: 229, name: "Bénin", description: "Pays d’Afrique de l’Ouest, capitale Porto-Novo." },
        { code: "PYS-022", indicator: 975, name: "Bhoutan", description: "Pays himalayen d’Asie, capitale Thimphou." },
        { code: "PYS-023", indicator: 375, name: "Biélorussie", description: "Pays d’Europe de l’Est, capitale Minsk." },
        { code: "PYS-024", indicator: 95, name: "Birmanie (Myanmar)", description: "Pays d’Asie du Sud-Est, capitale Naypyidaw." },
        { code: "PYS-025", indicator: 591, name: "Bolivie", description: "Pays d’Amérique du Sud, capitale La Paz/Sucre." },
        { code: "PYS-026", indicator: 387, name: "Bosnie-Herzégovine", description: "Pays d’Europe du Sud-Est, capitale Sarajevo." },
        { code: "PYS-027", indicator: 267, name: "Botswana", description: "Pays d’Afrique australe, capitale Gaborone." },
        { code: "PYS-028", indicator: 55, name: "Brésil", description: "Pays d’Amérique du Sud, capitale Brasília." },
        { code: "PYS-029", indicator: 673, name: "Brunei", description: "État d’Asie du Sud-Est, capitale Bandar Seri Begawan." },
        { code: "PYS-030", indicator: 359, name: "Bulgarie", description: "Pays d’Europe de l’Est, capitale Sofia." },
        { code: "PYS-031", indicator: 226, name: "Burkina Faso", description: "Pays d’Afrique de l’Ouest, capitale Ouagadougou." },
        { code: "PYS-032", indicator: 257, name: "Burundi", description: "Pays d’Afrique de l’Est, capitale Gitega." },
        { code: "PYS-033", indicator: 855, name: "Cambodge", description: "Pays d’Asie du Sud-Est, capitale Phnom Penh." },
        { code: "PYS-034", indicator: 237, name: "Cameroun", description: "Pays d’Afrique centrale, capitale Yaoundé." },
        { code: "PYS-035", indicator: 1, name: "Canada", description: "Pays d’Amérique du Nord, capitale Ottawa." },
        { code: "PYS-036", indicator: 238, name: "Cap-Vert", description: "Archipel d’Afrique de l’Ouest, capitale Praia." },
        { code: "PYS-037", indicator: 56, name: "Chili", description: "Pays d’Amérique du Sud, capitale Santiago." },
        { code: "PYS-038", indicator: 86, name: "Chine", description: "Pays d’Asie de l’Est, capitale Pékin." },
        { code: "PYS-039", indicator: 357, name: "Chypre", description: "Île méditerranéenne, capitale Nicosie." },
        { code: "PYS-040", indicator: 57, name: "Colombie", description: "Pays d’Amérique du Sud, capitale Bogota." },
        { code: "PYS-041", indicator: 269, name: "Comores", description: "Archipel d’Afrique, capitale Moroni." },
        { code: "PYS-042", indicator: 242, name: "Congo (Brazzaville)", description: "Pays d’Afrique centrale, capitale Brazzaville." },
        { code: "PYS-043", indicator: 243, name: "Congo (RDC)", description: "République Démocratique du Congo, capitale Kinshasa." },
        { code: "PYS-044", indicator: 850, name: "Corée du Nord", description: "Pays d’Asie de l’Est, capitale Pyongyang." },
        { code: "PYS-045", indicator: 82, name: "Corée du Sud", description: "Pays d’Asie de l’Est, capitale Séoul." },
        { code: "PYS-046", indicator: 506, name: "Costa Rica", description: "Pays d’Amérique centrale, capitale San José." },
        { code: "PYS-047", indicator: 225, name: "Côte d'Ivoire", description: "Pays d’Afrique de l’Ouest, capitale Yamoussoukro/Abidjan." },
        { code: "PYS-048", indicator: 385, name: "Croatie", description: "Pays d’Europe du Sud, capitale Zagreb." },
        { code: "PYS-049", indicator: 53, name: "Cuba", description: "Île des Caraïbes, capitale La Havane." },
        { code: "PYS-050", indicator: 45, name: "Danemark", description: "Pays d’Europe du Nord, capitale Copenhague." },
        { code: "PYS-051", indicator: 253, name: "Djibouti", description: "Pays de la Corne de l’Afrique, capitale Djibouti." },
        { code: "PYS-052", indicator: 1, name: "Dominique", description: "Île des Caraïbes, capitale Roseau." },
        { code: "PYS-053", indicator: 20, name: "Égypte", description: "Pays d’Afrique du Nord, capitale Le Caire." },
        { code: "PYS-054", indicator: 971, name: "Émirats arabes unis", description: "Pays du Golfe, capitale Abou Dabi." },
        { code: "PYS-055", indicator: 593, name: "Équateur", description: "Pays d’Amérique du Sud, capitale Quito." },
        { code: "PYS-056", indicator: 291, name: "Érythrée", description: "Pays de la Corne de l’Afrique, capitale Asmara." },
        { code: "PYS-057", indicator: 34, name: "Espagne", description: "Pays d’Europe du Sud, capitale Madrid." },
        { code: "PYS-058", indicator: 372, name: "Estonie", description: "Pays balte, capitale Tallinn." },
        { code: "PYS-059", indicator: 268, name: "Eswatini", description: "Pays d’Afrique australe, capitale Mbabane." },
        { code: "PYS-060", indicator: 1, name: "États-Unis", description: "Pays d’Amérique du Nord, capitale Washington D.C." },
        { code: "PYS-061", indicator: 251, name: "Éthiopie", description: "Pays de la Corne de l’Afrique, capitale Addis-Abeba." },
        { code: "PYS-062", indicator: 679, name: "Fidji", description: "Archipel d’Océanie, capitale Suva." },
        { code: "PYS-063", indicator: 358, name: "Finlande", description: "Pays nordique, capitale Helsinki." },
        { code: "PYS-064", indicator: 33, name: "France", description: "Pays d’Europe de l’Ouest, capitale Paris." },
        { code: "PYS-065", indicator: 241, name: "Gabon", description: "Pays d’Afrique centrale, capitale Libreville." },
        { code: "PYS-066", indicator: 220, name: "Gambie", description: "Petit pays d’Afrique de l’Ouest, capitale Banjul." },
        { code: "PYS-067", indicator: 995, name: "Géorgie", description: "Pays du Caucase, capitale Tbilissi." },
        { code: "PYS-068", indicator: 233, name: "Ghana", description: "Pays d’Afrique de l’Ouest, capitale Accra." },
        { code: "PYS-069", indicator: 30, name: "Grèce", description: "Pays d’Europe du Sud, capitale Athènes." },
        { code: "PYS-070", indicator: 1, name: "Grenade", description: "Île des Caraïbes, capitale Saint George's." },
        { code: "PYS-071", indicator: 502, name: "Guatemala", description: "Pays d’Amérique centrale, capitale Guatemala City." },
        { code: "PYS-072", indicator: 224, name: "Guinée", description: "Pays d’Afrique de l’Ouest, capitale Conakry." },
        { code: "PYS-073", indicator: 245, name: "Guinée-Bissau", description: "Pays d’Afrique de l’Ouest, capitale Bissau." },
        { code: "PYS-074", indicator: 240, name: "Guinée équatoriale", description: "Pays d’Afrique centrale, capitale Malabo." },
        { code: "PYS-075", indicator: 592, name: "Guyana", description: "Pays d’Amérique du Sud, capitale Georgetown." },
        { code: "PYS-076", indicator: 509, name: "Haïti", description: "Pays des Caraïbes, capitale Port-au-Prince." },
        { code: "PYS-077", indicator: 504, name: "Honduras", description: "Pays d’Amérique centrale, capitale Tegucigalpa." },
        { code: "PYS-078", indicator: 36, name: "Hongrie", description: "Pays d’Europe centrale, capitale Budapest." },
        { code: "PYS-079", indicator: 692, name: "Îles Marshall", description: "État insulaire du Pacifique, capitale Majuro." },
        { code: "PYS-080", indicator: 677, name: "Îles Salomon", description: "Archipel d’Océanie, capitale Honiara." },
        { code: "PYS-081", indicator: 91, name: "Inde", description: "Pays d’Asie du Sud, capitale New Delhi." },
        { code: "PYS-082", indicator: 62, name: "Indonésie", description: "Archipel d’Asie du Sud-Est, capitale Jakarta." },
        { code: "PYS-083", indicator: 964, name: "Irak", description: "Pays du Moyen-Orient, capitale Bagdad." },
        { code: "PYS-084", indicator: 98, name: "Iran", description: "Pays du Moyen-Orient, capitale Téhéran." },
        { code: "PYS-085", indicator: 353, name: "Irlande", description: "Pays d’Europe de l’Ouest, capitale Dublin." },
        { code: "PYS-086", indicator: 354, name: "Islande", description: "Île nordique, capitale Reykjavik." },
        { code: "PYS-087", indicator: 972, name: "Israël", description: "Pays du Moyen-Orient, capitale Jérusalem/Tel-Aviv." },
        { code: "PYS-088", indicator: 39, name: "Italie", description: "Pays d’Europe du Sud, capitale Rome." },
        { code: "PYS-089", indicator: 1, name: "Jamaïque", description: "Île des Caraïbes, capitale Kingston." },
        { code: "PYS-090", indicator: 81, name: "Japon", description: "Pays insulaire d’Asie de l’Est, capitale Tokyo." },
        { code: "PYS-091", indicator: 962, name: "Jordanie", description: "Pays du Moyen-Orient, capitale Amman." },
        { code: "PYS-092", indicator: 7, name: "Kazakhstan", description: "Pays d’Asie centrale, capitale Astana." },
        { code: "PYS-093", indicator: 254, name: "Kenya", description: "Pays d’Afrique de l’Est, capitale Nairobi." },
        { code: "PYS-094", indicator: 996, name: "Kirghizistan", description: "Pays d’Asie centrale, capitale Bichkek." },
        { code: "PYS-095", indicator: 686, name: "Kiribati", description: "État insulaire du Pacifique, capitale Tarawa-Sud." },
        { code: "PYS-096", indicator: 965, name: "Koweït", description: "Pays du Golfe, capitale Koweït City." },
        { code: "PYS-097", indicator: 856, name: "Laos", description: "Pays d’Asie du Sud-Est, capitale Vientiane." },
        { code: "PYS-098", indicator: 266, name: "Lesotho", description: "Pays enclavé d’Afrique australe, capitale Maseru." },
        { code: "PYS-099", indicator: 371, name: "Lettonie", description: "Pays balte, capitale Riga." },
        { code: "PYS-100", indicator: 961, name: "Liban", description: "Pays du Moyen-Orient, capitale Beyrouth." },
        { code: "PYS-101", indicator: 231, name: "Libéria", description: "Pays d’Afrique de l’Ouest, capitale Monrovia." },
        { code: "PYS-102", indicator: 218, name: "Libye", description: "Pays d’Afrique du Nord, capitale Tripoli." },
        { code: "PYS-103", indicator: 423, name: "Liechtenstein", description: "Petit pays d’Europe centrale, capitale Vaduz." },
        { code: "PYS-104", indicator: 370, name: "Lituanie", description: "Pays balte, capitale Vilnius." },
        { code: "PYS-105", indicator: 352, name: "Luxembourg", description: "Petit pays d’Europe de l’Ouest, capitale Luxembourg." },
        { code: "PYS-106", indicator: 389, name: "Macédoine du Nord", description: "Pays d’Europe du Sud-Est, capitale Skopje." },
        { code: "PYS-107", indicator: 261, name: "Madagascar", description: "Île d’Afrique de l’Est, capitale Antananarivo." },
        { code: "PYS-108", indicator: 60, name: "Malaisie", description: "Pays d’Asie du Sud-Est, capitale Kuala Lumpur." },
        { code: "PYS-109", indicator: 265, name: "Malawi", description: "Pays d’Afrique australe, capitale Lilongwe." },
        { code: "PYS-110", indicator: 960, name: "Maldives", description: "Archipel de l’océan Indien, capitale Malé." },
        { code: "PYS-111", indicator: 223, name: "Mali", description: "Pays d’Afrique de l’Ouest, capitale Bamako." },
        { code: "PYS-112", indicator: 356, name: "Malte", description: "Île de la Méditerranée, capitale La Valette." },
        { code: "PYS-113", indicator: 212, name: "Maroc", description: "Pays d’Afrique du Nord, capitale Rabat." },
        { code: "PYS-114", indicator: 230, name: "Maurice", description: "Île de l’océan Indien, capitale Port-Louis." },
        { code: "PYS-115", indicator: 222, name: "Mauritanie", description: "Pays d’Afrique de l’Ouest, capitale Nouakchott." },
        { code: "PYS-116", indicator: 52, name: "Mexique", description: "Pays d’Amérique du Nord, capitale Mexico." },
        { code: "PYS-117", indicator: 691, name: "Micronésie", description: "État insulaire du Pacifique, capitale Palikir." },
        { code: "PYS-118", indicator: 373, name: "Moldavie", description: "Pays d’Europe de l’Est, capitale Chișinău." },
        { code: "PYS-119", indicator: 377, name: "Monaco", description: "Petit État d’Europe, capitale Monaco." },
        { code: "PYS-120", indicator: 976, name: "Mongolie", description: "Pays d’Asie centrale, capitale Oulan-Bator." },
        { code: "PYS-121", indicator: 382, name: "Monténégro", description: "Pays d’Europe du Sud-Est, capitale Podgorica." },
        { code: "PYS-122", indicator: 258, name: "Mozambique", description: "Pays d’Afrique australe, capitale Maputo." },
        { code: "PYS-123", indicator: 264, name: "Namibie", description: "Pays d’Afrique australe, capitale Windhoek." },
        { code: "PYS-124", indicator: 674, name: "Nauru", description: "Île du Pacifique, capitale Yaren." },
        { code: "PYS-125", indicator: 977, name: "Népal", description: "Pays himalayen d’Asie du Sud, capitale Katmandou." },
        { code: "PYS-126", indicator: 505, name: "Nicaragua", description: "Pays d’Amérique centrale, capitale Managua." },
        { code: "PYS-127", indicator: 227, name: "Niger", description: "Pays d’Afrique de l’Ouest, capitale Niamey." },
        { code: "PYS-128", indicator: 234, name: "Nigeria", description: "Pays d’Afrique de l’Ouest, capitale Abuja." },
        { code: "PYS-129", indicator: 47, name: "Norvège", description: "Pays nordique, capitale Oslo." },
        { code: "PYS-130", indicator: 64, name: "Nouvelle-Zélande", description: "Pays d’Océanie, capitale Wellington." },
        { code: "PYS-131", indicator: 968, name: "Oman", description: "Pays du Golfe, capitale Mascate." },
        { code: "PYS-132", indicator: 256, name: "Ouganda", description: "Pays d’Afrique de l’Est, capitale Kampala." },
        { code: "PYS-133", indicator: 998, name: "Ouzbékistan", description: "Pays d’Asie centrale, capitale Tachkent." },
        { code: "PYS-134", indicator: 92, name: "Pakistan", description: "Pays d’Asie du Sud, capitale Islamabad." },
        { code: "PYS-135", indicator: 680, name: "Palaos", description: "État insulaire du Pacifique, capitale Ngerulmud." },
        { code: "PYS-136", indicator: 507, name: "Panama", description: "Pays d’Amérique centrale, capitale Panama City." },
        { code: "PYS-137", indicator: 675, name: "Papouasie-Nouvelle-Guinée", description: "Pays d’Océanie, capitale Port Moresby." },
        { code: "PYS-138", indicator: 595, name: "Paraguay", description: "Pays d’Amérique du Sud, capitale Asunción." },
        { code: "PYS-139", indicator: 31, name: "Pays-Bas", description: "Pays d’Europe de l’Ouest, capitale Amsterdam." },
        { code: "PYS-140", indicator: 51, name: "Pérou", description: "Pays d’Amérique du Sud, capitale Lima." },
        { code: "PYS-141", indicator: 63, name: "Philippines", description: "Archipel d’Asie du Sud-Est, capitale Manille." },
        { code: "PYS-142", indicator: 48, name: "Pologne", description: "Pays d’Europe centrale, capitale Varsovie." },
        { code: "PYS-143", indicator: 351, name: "Portugal", description: "Pays d’Europe du Sud-Ouest, capitale Lisbonne." },
        { code: "PYS-144", indicator: 974, name: "Qatar", description: "Pays du Golfe, capitale Doha." },
        { code: "PYS-145", indicator: 236, name: "République centrafricaine", description: "Pays d’Afrique centrale, capitale Bangui." },
        { code: "PYS-146", indicator: 1, name: "République dominicaine", description: "Pays des Caraïbes, capitale Saint-Domingue." },
        { code: "PYS-147", indicator: 420, name: "République tchèque", description: "Pays d’Europe centrale, capitale Prague." },
        { code: "PYS-148", indicator: 40, name: "Roumanie", description: "Pays d’Europe de l’Est, capitale Bucarest." },
        { code: "PYS-149", indicator: 44, name: "Royaume-Uni", description: "Pays d’Europe de l’Ouest, capitale Londres." },
        { code: "PYS-150", indicator: 7, name: "Russie", description: "Pays transcontinental Europe-Asie, capitale Moscou." },
        { code: "PYS-151", indicator: 250, name: "Rwanda", description: "Pays d’Afrique de l’Est, capitale Kigali." },
        { code: "PYS-152", indicator: 1, name: "Saint-Christophe-et-Niévès", description: "Île des Caraïbes, capitale Basseterre." },
        { code: "PYS-153", indicator: 378, name: "Saint-Marin", description: "Petit État d’Europe, capitale Saint-Marin." },
        { code: "PYS-154", indicator: 1, name: "Saint-Vincent-et-les-Grenadines", description: "Îles des Caraïbes, capitale Kingstown." },
        { code: "PYS-155", indicator: 1, name: "Sainte-Lucie", description: "Île des Caraïbes, capitale Castries." },
        { code: "PYS-156", indicator: 503, name: "Salvador", description: "Pays d’Amérique centrale, capitale San Salvador." },
        { code: "PYS-157", indicator: 685, name: "Samoa", description: "État insulaire d’Océanie, capitale Apia." },
        { code: "PYS-158", indicator: 239, name: "Sao Tomé-et-Principe", description: "Archipel d’Afrique centrale, capitale São Tomé." },
        { code: "PYS-159", indicator: 221, name: "Sénégal", description: "Pays d’Afrique de l’Ouest, capitale Dakar." },
        { code: "PYS-160", indicator: 381, name: "Serbie", description: "Pays d’Europe du Sud-Est, capitale Belgrade." },
        { code: "PYS-161", indicator: 248, name: "Seychelles", description: "Archipel de l’océan Indien, capitale Victoria." },
        { code: "PYS-162", indicator: 232, name: "Sierra Leone", description: "Pays d’Afrique de l’Ouest, capitale Freetown." },
        { code: "PYS-163", indicator: 65, name: "Singapour", description: "Ville-État d’Asie du Sud-Est, capitale Singapour." },
        { code: "PYS-164", indicator: 421, name: "Slovaquie", description: "Pays d’Europe centrale, capitale Bratislava." },
        { code: "PYS-165", indicator: 386, name: "Slovénie", description: "Pays d’Europe centrale, capitale Ljubljana." },
        { code: "PYS-166", indicator: 252, name: "Somalie", description: "Pays d’Afrique de l’Est, capitale Mogadiscio." },
        { code: "PYS-167", indicator: 249, name: "Soudan", description: "Pays d’Afrique du Nord-Est, capitale Khartoum." },
        { code: "PYS-168", indicator: 211, name: "Soudan du Sud", description: "Pays d’Afrique de l’Est, capitale Djouba." },
        { code: "PYS-169", indicator: 94, name: "Sri Lanka", description: "Île d’Asie du Sud, capitale Sri Jayawardenapura Kotte." },
        { code: "PYS-170", indicator: 46, name: "Suède", description: "Pays nordique, capitale Stockholm." },
        { code: "PYS-171", indicator: 41, name: "Suisse", description: "Pays d’Europe centrale, capitale Berne." },
        { code: "PYS-172", indicator: 597, name: "Suriname", description: "Pays d’Amérique du Sud, capitale Paramaribo." },
        { code: "PYS-173", indicator: 992, name: "Tadjikistan", description: "Pays d’Asie centrale, capitale Douchanbé." },
        { code: "PYS-174", indicator: 255, name: "Tanzanie", description: "Pays d’Afrique de l’Est, capitale Dodoma." },
        { code: "PYS-175", indicator: 235, name: "Tchad", description: "Pays d’Afrique centrale, capitale N'Djamena." },
        { code: "PYS-176", indicator: 66, name: "Thaïlande", description: "Pays d’Asie du Sud-Est, capitale Bangkok." },
        { code: "PYS-177", indicator: 670, name: "Timor oriental", description: "Pays d’Asie du Sud-Est, capitale Dili." },
        { code: "PYS-178", indicator: 228, name: "Togo", description: "Pays d’Afrique de l’Ouest, capitale Lomé." },
        { code: "PYS-179", indicator: 676, name: "Tonga", description: "État insulaire d’Océanie, capitale Nuku’alofa." },
        { code: "PYS-180", indicator: 1, name: "Trinité-et-Tobago", description: "Pays des Caraïbes, capitale Port of Spain." },
        { code: "PYS-181", indicator: 216, name: "Tunisie", description: "Pays d’Afrique du Nord, capitale Tunis." },
        { code: "PYS-182", indicator: 993, name: "Turkménistan", description: "Pays d’Asie centrale, capitale Achgabat." },
        { code: "PYS-183", indicator: 90, name: "Turquie", description: "Pays transcontinental Europe-Asie, capitale Ankara." },
        { code: "PYS-184", indicator: 688, name: "Tuvalu", description: "État insulaire du Pacifique, capitale Funafuti." },
        { code: "PYS-185", indicator: 380, name: "Ukraine", description: "Pays d’Europe de l’Est, capitale Kiev." },
        { code: "PYS-186", indicator: 598, name: "Uruguay", description: "Pays d’Amérique du Sud, capitale Montevideo." },
        { code: "PYS-187", indicator: 678, name: "Vanuatu", description: "État insulaire d’Océanie, capitale Port-Vila." },
        { code: "PYS-188", indicator: 379, name: "Vatican", description: "Petit État enclavé en Italie, capitale Vatican." },
        { code: "PYS-189", indicator: 58, name: "Venezuela", description: "Pays d’Amérique du Sud, capitale Caracas." },
        { code: "PYS-190", indicator: 84, name: "Viêt Nam", description: "Pays d’Asie du Sud-Est, capitale Hanoï." },
        { code: "PYS-191", indicator: 967, name: "Yémen", description: "Pays du Moyen-Orient, capitale Sanaa." },
        { code: "PYS-192", indicator: 260, name: "Zambie", description: "Pays d’Afrique australe, capitale Lusaka." },
        { code: "PYS-193", indicator: 263, name: "Zimbabwe", description: "Pays d’Afrique australe, capitale Harare." },
        { code: "PYS-194", indicator: 358, name: "Åland", description: "Archipel autonome de Finlande, capitale Mariehamn." },
        { code: "PYS-195", indicator: 679, name: "Fidji (détail supplémentaire)", description: "Archipel d’Océanie, capitale Suva." }
    ]

    for (const c of countries) {
        await prisma.country.create({
            data: c,
        })
    }

}

module.exports = countrySeeder;